apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bia-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: bia-frontend-ip
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: bia-managed-cert
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - host: cambobia.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bia-frontend
            port:
              number: 80
  - host: www.cambobia.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bia-frontend
            port:
              number: 80
  - host: api.cambobia.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bia-backend
            port:
              number: 80
