apiVersion: v1
kind: Secret
metadata:
  name: bia-secrets
type: Opaque
stringData:
  database-password: "BIA_Local_Admin_123!"
  jwt-secret: "your-super-long-secure-random-jwt-secret-here"
  initial-admin-password: "BIA_Local_Admin_123!"
